name: cms
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^2.3.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.6.0

  #LIBRARY ----------------------------------------------------------

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  shimmer: ^3.0.0
  animate_do: ^3.0.2
  path_provider: ^2.0.11
  dio: ^5.1.2

  cached_network_image: ^3.2.2
  dio_cache_interceptor: ^3.3.1
  pull_to_refresh: ^2.0.0
  badges: ^3.1.1
  slide_digital_clock: ^1.0.3
  url_launcher: ^6.1.10
  #  syncfusion_flutter_calendar: ^20.2.49
  table_calendar: ^3.0.7
  flutter_advanced_drawer: ^1.3.2
  pretty_dio_logger: ^1.1.1
  permission_handler: ^11.1.0
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.2.3
  geolocator: ^10.1.0
  location: ^5.0.3
  flutter_typeahead: ^5.0.1
  flutter_local_notifications: ^16.2.0
  flutter_native_timezone: ^2.0.0
  image: ^4.0.17
  device_info_plus: ^9.0.0
  line_icons: ^2.0.1
  flutter_keyboard_visibility: ^5.4.0
  carousel_slider: ^4.2.1
  page_view_dot_indicator: ^2.1.0
  flutter_file_downloader: ^1.1.0+1
  image_picker: ^1.0.5
  camera: ^0.10.4
  realm: ^1.2.0

  #FIREBASE ------------------------------
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_database: ^10.2.0
  cloud_firestore: ^4.7.0
  marquee: ^2.2.3
  syncfusion_flutter_calendar: ^24.1.41
  calendar_view: ^1.0.0
  qr_code_scanner: ^1.0.1
  flutter_widget_from_html_core: ^0.14.9
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.5
  another_flushbar: ^1.12.30
  flutter_animate: ^4.2.0+1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
 

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/cmslogo.png
    - assets/images/cmsbottom_home_banner.jpg
    - assets/images/cmsteacher.jpg
    - assets/images/cmstahfiz.jpg
    - assets/images/cmspalestine.jpg
    - assets/sample_json/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

    # - family: PoppinsLight
    #   fonts:
    #     - asset: assets/fonts/Poppins-Light.ttf

    # - family: PoppinsMedium
    #   fonts:
    #     - asset: assets/fonts/Poppins-Medium.ttf

    # - family: PoppinsSemiBold
    #   fonts:
    #     - asset: assets/fonts/Poppins-SemiBold.ttf

    # - family: PoppinsBold
    #   fonts:
    #     - asset: assets/fonts/Poppins-Bold.ttf
